# SPDX-FileCopyrightText: 2022 Fluid Attacks and Makes contributors
#
# SPDX-License-Identifier: MIT

---
steps:
  - label: step-1
    plugins:
      - docker#v5.2.0:
          image: "ghcr.io/fluidattacks/makes:22.11"
          always-pull: true
          propagate-environment: true
          privileged: false
          command: ["m", ".", "/helloWorld", "1"]
  - label: step-2
    plugins:
      - docker#v5.2.0:
          image: "ghcr.io/fluidattacks/makes:22.11"
          always-pull: true
          propagate-environment: true
          privileged: false
          command: ["m", ".", "/helloWorld", "2"]
  - label: step-3
    plugins:
      - docker#v5.2.0:
          image: "ghcr.io/fluidattacks/makes:22.11"
          always-pull: true
          propagate-environment: true
          privileged: false
          command: ["m", ".", "/helloWorld", "3"]
  - label: step-4
    plugins:
      - docker#v5.2.0:
          image: "ghcr.io/fluidattacks/makes:22.11"
          always-pull: true
          propagate-environment: true
          privileged: false
          command: ["m", ".", "/helloWorld", "4"]
