# SPDX-FileCopyrightText: 2022 Fluid Attacks and Makes contributors
#
# SPDX-License-Identifier: MIT

---
useTabs: false
semi: true
trailingComma: es5
singleQuote: false
tabWidth: 2
bracketSpacing: true
arrowParens: always
