# SPDX-FileCopyrightText: 2022 Fluid Attacks and Makes contributors
#
# SPDX-License-Identifier: MIT

[book]
authors = ["Fluid Attacks"]
language = "en"
multilingual = false
src = "src"
title = "Makes"

[output.html]
default-theme = "light"
edit-url-template = "https://github.com/fluidattacks/makes/edit/main/docs/{path}"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/fluidattacks/makes"
git-repository-icon = "fa-github"
site-url = "/makes"

[output.html.fold]
enable = false
level = 0
