site_name: Makes Documentation
site_url: https://fluidattacks.github.io/makes/
site_description: Documentation for Makes
site_author: Fluid Attacks
repo_url: https://github.com/fluidattacks/makes
repo_name: Makes
copyright: Copyright © 2023 Fluid Attacks, We hack your software. All rights reserved.

nav:
  - index.md
  - getting-started.md
  - configuring-ci-cd.md
  - versioning.md
  - API:
      - builtins:
          - api/builtins/index.md
          - api/builtins/database.md
          - api/builtins/deploy.md
          - api/builtins/development.md
          - api/builtins/environment.md
          - api/builtins/examples.md
          - api/builtins/format.md
          - api/builtins/framework-configuration.md
          - api/builtins/lint.md
          - api/builtins/monitoring.md
          - api/builtins/performance.md
          - api/builtins/secrets.md
          - api/builtins/security.md
          - api/builtins/test.md
          - api/builtins/utilities.md
      - extensions:
          - api/extensions/index.md
          - api/extensions/fundamentals.md
          - api/extensions/containers.md
          - api/extensions/fetchers.md
          - api/extensions/format-conversion.md
          - api/extensions/git.md
          - api/extensions/node.js.md
          - api/extensions/others.md
          - api/extensions/patchers.md
          - api/extensions/python.md
          - api/extensions/ruby.md
  - architecture.md
  - contributing.md
  - governance.md
  - Security:
      - security/introduction.md
      - security/assurance.md
      - security/design-principles.md
      - security/slsa.md
      - security/threat-model.md

strict: true
docs_dir: src
theme:
  name: material
  logo: assets/favicon.svg
  favicon: assets/favicon.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.instant
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
