site_name: Makes Documentation
site_url: https://fluidattacks.github.io/makes/
site_description: Documentation for Makes
site_author: Fluid Attacks
repo_url: https://github.com/fluidattacks/makes
repo_name: Makes
copyright: Copyright © 2023 Fluid Attacks, We hack your software. All rights reserved.

nav:
  - index.md
  - configuring-ci-cd.md
  - versioning.md
  - API:
      - makes.nix:
          - api/makes.nix/index.md
          - api/makes.nix/database.md
          - api/makes.nix/deploy.md
          - api/makes.nix/development.md
          - api/makes.nix/environment.md
          - api/makes.nix/examples.md
          - api/makes.nix/format.md
          - api/makes.nix/framework-configuration.md
          - api/makes.nix/lint.md
          - api/makes.nix/monitoring.md
          - api/makes.nix/performance.md
          - api/makes.nix/secrets.md
          - api/makes.nix/security.md
          - api/makes.nix/test.md
          - api/makes.nix/utilities.md
  - architecture.md
  - contributing.md
  - governance.md
  - Security:
      - security/introduction.md
      - security/assurance.md
      - security/design-principles.md
      - security/slsa.md
      - security/threat-model.md

strict: true
docs_dir: src
theme:
  name: material
  logo: assets/favicon.svg
  favicon: assets/favicon.svg
  palette:
    primary: deep purple
    accent: purple
  features:
    - content.code.copy
    - navigation.instant
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
