concurrency:
  cancel-in-progress: true
  group: ${{ github.actor }}
jobs:
  deployContainerImage_makesGitHub:
    if: ${{ github.repository == 'fluidattacks/makes' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: docker://docker.io/nixos/nix@sha256:2e810dab4086d318d8559b3bd5dce46ce4af3cde48a190af9527e0228aa9580b
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
        with:
          args: sh -c "nix-env -if . && m . /deployContainerImage/makesGitHub"

  releaseGitHub:
    if: ${{ github.repository == 'fluidattacks/makes' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: richardsimko/update-tag@5bd0e05b035e02d5da3768dbdcfc4e5e0908623e
        with:
          tag_name: "22.05"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: johnwbyrd/update-release@1d5ec4791e40507e5eca3b4dbf90f0b27e7e4979
        with:
          files: README.md
          release: "22.05"
          prerelease: true
          tag: "22.05"
          token: ${{ github.token }}
name: prod
on:
  push:
    branches: [main]
